name: Force Update bot.sh (PAT)

on:
  workflow_dispatch:

permissions:
  contents: write

jobs:
  force-update:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout (no default creds)
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          persist-credentials: false

      - name: Configure git
        run: |
          set -euo pipefail
          git config user.name  "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"

      - name: Sync to latest main
        run: |
          set -euo pipefail
          git fetch origin main
          git checkout -B main origin/main
          git reset --hard origin/main

      - name: Update bin/bot.sh with recipes
        run: |
          set -euo pipefail
          mkdir -p bin
          cat > bin/bot.sh <<'EOF'
              #!/usr/bin/env bash

              # ./bin/bot.sh <recipe> to push a cooking recipe forced style
              set -euo pipefail
              recipe_pancakes(){ cat <<TXT
              Fluffy Pancakes
              Ingredients:
              - 1 cup flour
              - 2 tbsp sugar
              - 2 tsp baking powder
              - 1/4 tsp salt
              - 1 cup milk
              - 1 egg
              - 2 tbsp melted butter
              Steps:
              1) Whisk dry.
              2) Add wet, mix just until combined.
              3) Cook 2–3 min/side on medium.
              TXT
              }
              recipe_garlic_pasta(){ cat <<TXT
              Garlic Butter Pasta
              Ingredients:
              - 8 oz pasta
              - 3 tbsp butter
              - 3 cloves garlic, minced
              - 1/4 cup grated parmesan
              - Salt, pepper, parsley
              Steps:
              1) Boil pasta.
              2) Melt butter, sauté garlic 30s.
              3) Toss pasta + parmesan; season.
              TXT
              }
              main(){
                case "${1:-}" in
                  pancakes) recipe_pancakes ;;
                  garlic-pasta|garlic_pasta) recipe_garlic_pasta ;;
                  *) echo "Recipes: pancakes, garlic-pasta" >&2; exit 2 ;;
                esac
              }
              main "$@"
              EOF
          chmod +x bin/bot.sh
          git add bin/bot.sh
          git commit -m "feat(recipes): update bin/bot.sh" || echo "No changes to commit"

      - name: Set remote to use PAT
        env:
          PAT: ${{ secrets.GIT_FORCE }}
        run: |
          set -euo pipefail
          git remote set-url origin "https://x-access-token:${PAT}@github.com/${{ github.repository }}.git"

      - name: Force push to main (porcelain)
        run: |
          set -euo pipefail
          git push --force --porcelain origin HEAD:main
