name: Force Update Bot

on:
  workflow_dispatch:   

permissions:
  contents: write    

jobs:
  force-update:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout full history
        uses: actions/checkout@v4
        with:
          fetch-depth: 0   # required to allow force

      - name: Configure git
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"

      - name: Create dummy commit
        run: |
          echo "testing -- force $(date)" > force-test.txt
          git add force-test.txt
          git commit -m "testing -- force"

      - name: Force push to main
        run: |
          git push origin HEAD:main --force
